### ISSUE TITLE
API: BaseState definition

### ISSUE THREAD

**Issue by leonhard-s** [auto-pl/apl-website#5]
I will start implementing the REST API soon and would like to clarify/define a few details before I get started.

Here is the current interface definition for quick reference (commit hash 539783f):

https://github.com/auto-pl/apl-website/blob/539783f6c078b69db42c4c53555cb71525f6024a/src/interfaces/continent.ts#L22-L41

- I think we should include base IDs in the response for consistency. Dealing with string literals for hover events and other callbacks just feels wrong. 😂 We would still include the names in a separate key (e.g. `faction_id` and `faction_name`), of course.
(The same goes for factions and continents.)
- Leaderboards are excruciatingly difficult to estimate and keep accurate. The population tracking system may be able to provide reasonable estimates for total populations, but positioning individual, highly mobile players like aircraft pilots over the duration of the cap to accumulate their score may be impossible to do with any degree of accuracy.
- It is uncertain whether we will be able to get base priority scores out of the AI at any point. I will put this down on the roadmap, but it is very much a "nice to have" endgame option.

Most importantly, I rather we remove interface components that are not yet implemented until they are ready instead of having to alter or remove them in production. For TS, this could be as simple as commenting them out or moving them to a dormant branch until the backend is ready to supply such information.

**Comment by leonhard-s** [comment]
More open questions:

- What will the frontend queries look like? I was assuming we would use integer IDs, but there is no reason to do so (see #4).
- We may want to use a `last_captured` UTC timestamp instead and calculate `time_held` locally. It makes most sense update these times once a second client-side, so a reference timestamp that can be compared to the current time.
- Do we prefer fewer, large queries or many small ones? The former is redundant, especially if we start moving base updates and similar real-time events to the websocket connection instead.

**Comment by SMC242** [comment]
- No leaderboard is ok
- Base id is ok
    - This can be wrapped into a `BaseInfo: { base_name: string, base_id: string }`
- I need a priority score for animating which bases need attention. It should range between 0 and 100
- Calculating `time_held` is fine
- `last_captured` can be wrapped into a `CaptureInfo: { faction: string, when: Date, outfit_id: string | null }`
- My gut feeling is that many queries would be better for mobile and easier to get specific information with

**Comment by leonhard-s** [comment]
> My gut feeling is that many queries would be better for mobile and easier to get specific information with

Yeah, true - and I think we are quite free to change the specification as needed; most of the high-volume data will eventually move to websocket anyway so I'm not too fussed about REST API volume just yet (prototype hubris ensues).

Regarding IDs vs names: As we discussed earlier; we backend people (tm) will always use IDs for simplicity; what you get back from the REST interface is really a matter of preference and can be changed on the API level at any point. Which do you intend to use for the front-end, integer IDs (`4092`, etc.) or string identifiers (e.g. `indar-comm-array`)? I think sticking to that makes the most sense.

I like the base attention system, but I think it's safest to either disable this system initially or use the population system. An AI being able to identify priority bases is months away.

**Comment by SMC242** [comment]
- A numeric ID is more conventional + smaller
- The priority query can just spit out a number based on population ratio until the AI is there

**Comment by leonhard-s** [comment]
Alright, I'll just use the internal base IDs for now; should make debugging and troubleshooting easier as well.

Population estimates are still in the works, the initial version will return `-1.0` for every base initially, but I'll include it in the endpoint.

**Comment by SMC242** [comment]
Cheese apple
