### ISSUE TITLE
Server interface

### ISSUE THREAD

**Issue by SMC242** [auto-pl/apl-website#6]
As mentioned in 17331f6a7f70847aac8aef5675bb0655bc75d3d4 , emitting `Continents` for the `Server` interface is a bit much

Maybe there should be a `PartialContinent` interface without the `BaseState`s

@leonhard-s

**Comment by leonhard-s** [comment]
I think that might be better, yeah. I still don't see a use case for the full-scope `Continents` view including the `BaseState` array/map.

The main example for continent overviews would be the continent picker, and we don't need full population data there. I guess having a preview of what the continent looks like as part of the continent switching GUI would be neat, so base ownership data would be handy to have available (plus it's compact).

The inclusion of population data by faction quintuples the size of the continent payload, so we should make sure we need it before flinging that much data around.

**Comment by SMC242** [comment]
Suggested change: 
```typescript
readonly base_states: Array
<BaseState>;  // getter method that executes the base state query
```

**Comment by leonhard-s** [comment]
That seems good for now, yeah - that was we don't fetch the full dataset each time and stil have a convenient way to fetch the base state if needed (e.g. if the continent is selected from the switching GUI).

**Comment by SMC242** [comment]
Ok I will implement it
